# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-hellocmake"
BBFILE_PATTERN_meta-hellocmake = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-hellocmake = "6"

LAYERDEPENDS_meta-hellocmake = "core"
LAYERSERIES_COMPAT_meta-hellocmake = "kirkstone"
